[project]
name = "test"
version = "0"
requires-python = ">=3.13"

dependencies = [
    "ddtrace>=3.2.1",
    "ipdb>=0.13.13",
    "sentry-sdk",
]

[tool.uv.sources]
sentry-sdk = { path = "../../sentry-python", editable = true }
