[project]
name = "test"
version = "0"
requires-python = ">=3.13"

dependencies = [
    "ipdb>=0.13.13",
    "pytest-rerunfailures>=15.0",
    "pytest-sentry>=0.3.3",
    "sentry-sdk",
]

[tool.uv.sources]
sentry-sdk = { path = "../../sentry-python", editable = true }
