[project]
name = "test"
version = "0"
requires-python = ">=3.13"

dependencies = [
    "ipdb>=0.13.13",
    "sentry-sdk[fastapi,asyncpg,rq]",
]

[tool.uv.sources]
sentry-sdk = { path = "../../sentry-python", editable = true }
