[project]
name = "test"
version = "0"
requires-python = ">=3.12"

dependencies = [
    "ipdb>=0.13.13",
    "openai>=1.77.0",
    "sentry-sdk",
    "tiktoken>=0.9.0",
]

[tool.uv.sources]
sentry-sdk = { path = "../../sentry-python", editable = true }
