[project]
name = "test"
version = "0"
requires-python = ">=3.12"

dependencies = [
    "fastapi>=0.115.12",
    "ipdb>=0.13.13",
    "sentry-sdk",
    "uvicorn>=0.34.0",
]

[tool.uv.sources]
sentry-sdk = { path = "../../sentry-python", editable = true }
