[project]
name = "test"
version = "0"
requires-python = ">=3.12"

dependencies = [
    "ipdb>=0.13.13",
    "sentry-sdk",
    "openai-agents>0.0.16",
    "simpleeval>=0.9.13",
]

[tool.uv.sources]
sentry-sdk = { path = "../../sentry-python", editable = true }
