# Generated by Django 5.2.5 on 2025-08-06 15:28

from django.db import migrations
from django.utils import timezone


def add_sample_greetings(apps, schema_editor):
    """Add 5 sample greeting items to demonstrate the connection pooling"""
    Greeting = apps.get_model('hello', 'Greeting')

    sample_greetings = [
        {"message": "Hello, World!", "count": 42},
        {"message": "Welcome to Django Connection Pooling!", "count": 15},
        {"message": "Greetings from PostgreSQL!", "count": 28},
        {"message": "Connection pooling is awesome!", "count": 7},
        {"message": "Hello from Sentry SDK!", "count": 99},
    ]

    for greeting_data in sample_greetings:
        Greeting.objects.create(
            message=greeting_data["message"],
            count=greeting_data["count"],
            created_at=timezone.now()
        )


def remove_sample_greetings(apps, schema_editor):
    """Remove the sample greetings if migration is reversed"""
    Greeting = apps.get_model('hello', 'Greeting')
    sample_messages = [
        "Hello, World!",
        "Welcome to Django Connection Pooling!",
        "Greetings from PostgreSQL!",
        "Connection pooling is awesome!",
        "Hello from Sentry SDK!",
    ]
    Greeting.objects.filter(message__in=sample_messages).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("hello", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(add_sample_greetings, remove_sample_greetings),
    ]
