# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: helloworld2.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11helloworld2.proto\x12\x0bhelloworld2\"\x1d\n\rHelloRequest2\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1e\n\x0bHelloReply2\x12\x0f\n\x07message\x18\x01 \x01(\t2\xf3\x01\n\x08Greeter2\x12\x43\n\tSayHello2\x12\x1a.helloworld2.HelloRequest2\x1a\x18.helloworld2.HelloReply2\"\x00\x12P\n\x14SayHelloStreamReply2\x12\x1a.helloworld2.HelloRequest2\x1a\x18.helloworld2.HelloReply2\"\x00\x30\x01\x12P\n\x12SayHelloBidiStrea2\x12\x1a.helloworld2.HelloRequest2\x1a\x18.helloworld2.HelloReply2\"\x00(\x01\x30\x01\x42\x32\n\x15io.sentry.helloworld2B\x10HelloWorldProto2P\x01\xa2\x02\x04HLW2b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'helloworld2_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\025io.sentry.helloworld2B\020HelloWorldProto2P\001\242\002\004HLW2'
  _globals['_HELLOREQUEST2']._serialized_start=34
  _globals['_HELLOREQUEST2']._serialized_end=63
  _globals['_HELLOREPLY2']._serialized_start=65
  _globals['_HELLOREPLY2']._serialized_end=95
  _globals['_GREETER2']._serialized_start=98
  _globals['_GREETER2']._serialized_end=341
# @@protoc_insertion_point(module_scope)
