[project]
name = "test"
version = "0"
requires-python = ">=3.12"

dependencies = [
    "celery==5.3.6",
    "redis",
    "ipdb>=0.13.13",
    "sentry-sdk",
]

[tool.uv.sources]
sentry-sdk = { path = "../../sentry-python", editable = true }
